### ISSUE TITLE
What are the default algod_address and algod_token?

### ISSUE THREAD

**Issue by JeremyEnglert** [danmurphy1217/algorand-quickstart#9]
For example, when you use Algorand's Sandbox (https://github.com/algorand/sandbox), it creates the following;

```
algod:
address: http://localhost:4001
token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

Does quick-algo do something similar?

PS - Super bad ass tool! I was having major headaches getting a node setup and this simplified it a ton.

**Comment by danmurphy1217** [comment]
@JeremyEnglert

`algod_token` is stored in (assuming you download the script to your $HOME dir) `~/node/data/algod.token` and `algod_address` is stored in (same assumption as above) `~/node/data/algod.net`. 

Yes, this script does something very similar - each time you start a node you are assigned an API key that you can use to interact with the node on the URL and port that it is running. The URL and port never change with `quick-algo`, it will always run on `127.0.0.1:8080`


This tool was built to make the process way easier, so I'm glad you found it. Give it a spin and let me know if you run into any issues. It's been robustly tested on mac and ubuntu, lesser so on windows.

**Comment by JeremyEnglert** [comment]
Thank you!
